package mibs.asterisk.agi.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import mibs.asterisk.agi.main.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App(App.CONFIG_NAME);
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
